set_property IOSTANDARD LVCMOS33 [get_ports rst_0]
set_property PACKAGE_PIN D20 [get_ports rst_0]
set_property PACKAGE_PIN L15 [get_ports busy_0]
set_property PACKAGE_PIN Y19 [get_ports sout_0]
set_property PACKAGE_PIN U18 [get_ports parityselect_0]
set_property IOSTANDARD LVCMOS33 [get_ports parityselect_0]
set_property IOSTANDARD LVCMOS33 [get_ports busy_0]
set_property IOSTANDARD LVCMOS33 [get_ports sout_0]
