# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA_project/AXI_UART_RX/AXI_UART_RX.srcs/sources_1/bd/UART_RX_BD/ip/UART_RX_BD_rst_ps7_0_50M_0/UART_RX_BD_rst_ps7_0_50M_0.xci
# IP: The module: 'UART_RX_BD_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/AXI_UART_RX/AXI_UART_RX.gen/sources_1/bd/UART_RX_BD/ip/UART_RX_BD_rst_ps7_0_50M_0/UART_RX_BD_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_RX_BD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_project/AXI_UART_RX/AXI_UART_RX.gen/sources_1/bd/UART_RX_BD/ip/UART_RX_BD_rst_ps7_0_50M_0/UART_RX_BD_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_RX_BD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_project/AXI_UART_RX/AXI_UART_RX.gen/sources_1/bd/UART_RX_BD/ip/UART_RX_BD_rst_ps7_0_50M_0/UART_RX_BD_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_RX_BD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FPGA_project/AXI_UART_RX/AXI_UART_RX.srcs/sources_1/bd/UART_RX_BD/ip/UART_RX_BD_rst_ps7_0_50M_0/UART_RX_BD_rst_ps7_0_50M_0.xci
# IP: The module: 'UART_RX_BD_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/AXI_UART_RX/AXI_UART_RX.gen/sources_1/bd/UART_RX_BD/ip/UART_RX_BD_rst_ps7_0_50M_0/UART_RX_BD_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_RX_BD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_project/AXI_UART_RX/AXI_UART_RX.gen/sources_1/bd/UART_RX_BD/ip/UART_RX_BD_rst_ps7_0_50M_0/UART_RX_BD_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_RX_BD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA_project/AXI_UART_RX/AXI_UART_RX.gen/sources_1/bd/UART_RX_BD/ip/UART_RX_BD_rst_ps7_0_50M_0/UART_RX_BD_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_RX_BD_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
