# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA_project/zynq_axi_7seg/zynq_axi_7seg.srcs/sources_1/bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_processing_system7_0_0/zynq_axi_7seg_bd_processing_system7_0_0.xci
# IP: The module: 'zynq_axi_7seg_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/zynq_axi_7seg/zynq_axi_7seg.gen/sources_1/bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_processing_system7_0_0/zynq_axi_7seg_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_7seg_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/FPGA_project/zynq_axi_7seg/zynq_axi_7seg.srcs/sources_1/bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_processing_system7_0_0/zynq_axi_7seg_bd_processing_system7_0_0.xci
# IP: The module: 'zynq_axi_7seg_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/zynq_axi_7seg/zynq_axi_7seg.gen/sources_1/bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_processing_system7_0_0/zynq_axi_7seg_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_axi_7seg_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
