# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_basys/zynq_basys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_basys || ORIG_REF_NAME==zynq_basys} -quiet] -quiet

# IP: bd/zynq_basys/ip/zynq_basys_processing_system7_0_0/zynq_basys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_basys_processing_system7_0_0 || ORIG_REF_NAME==zynq_basys_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_basys/ip/zynq_basys_ps7_0_axi_periph_0/zynq_basys_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_basys_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_basys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_basys/ip/zynq_basys_rst_ps7_0_50M_0/zynq_basys_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_basys_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_basys_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq_basys/ip/zynq_basys_system_ila_0_0/zynq_basys_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_basys_system_ila_0_0 || ORIG_REF_NAME==zynq_basys_system_ila_0_0} -quiet] -quiet

# IP: bd/zynq_basys/ip/zynq_basys_myip_slave_lite_v1_0_1_0/zynq_basys_myip_slave_lite_v1_0_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_basys_myip_slave_lite_v1_0_1_0 || ORIG_REF_NAME==zynq_basys_myip_slave_lite_v1_0_1_0} -quiet] -quiet

# IP: bd/zynq_basys/ip/zynq_basys_auto_pc_0/zynq_basys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_basys_auto_pc_0 || ORIG_REF_NAME==zynq_basys_auto_pc_0} -quiet] -quiet

# XDC: c:/FPGA_project/zynq_basic_system/zynq_basic_system.gen/sources_1/bd/zynq_basys/zynq_basys_ooc.xdc
