# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zynq_bd.xdc

# Block Designs: bd/zynq_bd/zynq_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd || ORIG_REF_NAME==zynq_bd} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_processing_system7_0_0/zynq_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_processing_system7_0_0 || ORIG_REF_NAME==zynq_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_myip_slave_lite_v1_0_0_0/zynq_bd_myip_slave_lite_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_myip_slave_lite_v1_0_0_0 || ORIG_REF_NAME==zynq_bd_myip_slave_lite_v1_0_0_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_auto_pc_0/zynq_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_auto_pc_0 || ORIG_REF_NAME==zynq_bd_auto_pc_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_ps7_0_axi_periph_0/zynq_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_bd/ip/zynq_bd_rst_ps7_0_50M_0/zynq_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_bd_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/FPGA_project/axi_dip2led/axi_dip2led.gen/sources_1/bd/zynq_bd/zynq_bd_ooc.xdc
