set_property SRC_FILE_INFO {cfile:C:/FPGA_project/zynq_axi_7seg/zynq_axi_7seg.srcs/constrs_1/new/zynq_axi_7seg.xdc rfile:../../../zynq_axi_7seg.srcs/constrs_1/new/zynq_axi_7seg.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {AN_0[0]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports {AN_0[1]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports {AN_0[2]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T10 [get_ports {AN_0[3]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {AN_0[4]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {AN_0[5]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {AN_0[6]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports {SW_0[0]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports {SW_0[1]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {SW_0[2]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {SW_0[3]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports CA_0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports rst_0]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list zynq_axi_7seg_bd_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[0]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[1]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[2]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[3]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[4]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[5]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[6]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[7]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[8]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[9]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[10]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[11]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[12]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[13]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[14]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[15]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[16]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[17]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[18]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[19]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[20]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[21]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[22]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[23]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[24]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[25]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[26]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[27]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[28]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[29]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[30]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[31]}]]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {zynq_axi_7seg_bd_i/axi_slve_0/inst/DIGIT[0]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/DIGIT[1]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/DIGIT[2]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/DIGIT[3]}]]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
