# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA_project/AXI_UART/AXI_UART.srcs/sources_1/bd/AXI_UART_TX/ip/AXI_UART_TX_processing_system7_0_0/AXI_UART_TX_processing_system7_0_0.xci
# IP: The module: 'AXI_UART_TX_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART_TX/ip/AXI_UART_TX_processing_system7_0_0/AXI_UART_TX_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_TX_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/FPGA_project/AXI_UART/AXI_UART.srcs/sources_1/bd/AXI_UART_TX/ip/AXI_UART_TX_processing_system7_0_0/AXI_UART_TX_processing_system7_0_0.xci
# IP: The module: 'AXI_UART_TX_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_project/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART_TX/ip/AXI_UART_TX_processing_system7_0_0/AXI_UART_TX_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_UART_TX_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
