set_property IOSTANDARD LVCMOS33 [get_ports {AN_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_0[0]}]
set_property PACKAGE_PIN W14 [get_ports {AN_0[0]}]
set_property PACKAGE_PIN Y14 [get_ports {AN_0[1]}]
set_property PACKAGE_PIN T11 [get_ports {AN_0[2]}]
set_property PACKAGE_PIN T10 [get_ports {AN_0[3]}]
set_property PACKAGE_PIN V16 [get_ports {AN_0[4]}]
set_property PACKAGE_PIN W16 [get_ports {AN_0[5]}]
set_property PACKAGE_PIN V12 [get_ports {AN_0[6]}]
set_property PACKAGE_PIN Y18 [get_ports {SW_0[0]}]
set_property PACKAGE_PIN Y19 [get_ports {SW_0[1]}]
set_property PACKAGE_PIN Y16 [get_ports {SW_0[2]}]
set_property PACKAGE_PIN Y17 [get_ports {SW_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports CA_0]
set_property PACKAGE_PIN W13 [get_ports CA_0]

set_property IOSTANDARD LVCMOS33 [get_ports rst_0]
set_property PACKAGE_PIN D20 [get_ports rst_0]

set_property MARK_DEBUG false [get_nets {AN_0[0]}]
set_property MARK_DEBUG false [get_nets {AN_0[1]}]
set_property MARK_DEBUG false [get_nets {AN_0[2]}]
set_property DONT_TOUCH false [get_nets {AN_0[3]}]
set_property DONT_TOUCH true [get_nets {AN_0[4]}]
set_property MARK_DEBUG false [get_nets {AN_0[4]}]
set_property MARK_DEBUG false [get_nets {AN_0[5]}]
set_property MARK_DEBUG false [get_nets {AN_0[3]}]
set_property MARK_DEBUG false [get_nets {AN_0[6]}]

connect_debug_port u_ila_0/probe0 [get_nets [list {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[0]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[1]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[2]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[3]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[4]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[5]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[6]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[7]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[8]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[9]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[10]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[11]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[12]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[13]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[14]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[15]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[16]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[17]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[18]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[19]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[20]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[21]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[22]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[23]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[24]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[25]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[26]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[27]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[28]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[29]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[30]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg1[31]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list zynq_axi_7seg_bd_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {zynq_axi_7seg_bd_i/axi_slve_0/inst/DIGIT[4]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/DIGIT[5]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/DIGIT[6]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/DIGIT[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[0]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[1]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[2]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[3]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[4]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[5]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[6]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[7]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[8]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[9]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[10]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[11]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[12]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[13]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[14]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[15]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[16]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[17]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[18]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[19]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[20]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[21]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[22]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[23]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[24]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[25]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[26]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[27]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[28]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[29]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[30]} {zynq_axi_7seg_bd_i/axi_slve_0/inst/slv_reg0[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
