# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/axi_uart_rx.xdc

# Block Designs: bd/UART_RX_BD/UART_RX_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX_BD || ORIG_REF_NAME==UART_RX_BD} -quiet] -quiet

# IP: bd/UART_RX_BD/ip/UART_RX_BD_processing_system7_0_0/UART_RX_BD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX_BD_processing_system7_0_0 || ORIG_REF_NAME==UART_RX_BD_processing_system7_0_0} -quiet] -quiet

# IP: bd/UART_RX_BD/ip/UART_RX_BD_axi_interconnect_0_0/UART_RX_BD_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX_BD_axi_interconnect_0_0 || ORIG_REF_NAME==UART_RX_BD_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/UART_RX_BD/ip/UART_RX_BD_rst_ps7_0_50M_0/UART_RX_BD_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX_BD_rst_ps7_0_50M_0 || ORIG_REF_NAME==UART_RX_BD_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/UART_RX_BD/ip/UART_RX_BD_myip_slave_lite_v1_0_0_0/UART_RX_BD_myip_slave_lite_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX_BD_myip_slave_lite_v1_0_0_0 || ORIG_REF_NAME==UART_RX_BD_myip_slave_lite_v1_0_0_0} -quiet] -quiet

# IP: bd/UART_RX_BD/ip/UART_RX_BD_UART_RX_ctl_0_0/UART_RX_BD_UART_RX_ctl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX_BD_UART_RX_ctl_0_0 || ORIG_REF_NAME==UART_RX_BD_UART_RX_ctl_0_0} -quiet] -quiet

# IP: bd/UART_RX_BD/ip/UART_RX_BD_auto_pc_0/UART_RX_BD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==UART_RX_BD_auto_pc_0 || ORIG_REF_NAME==UART_RX_BD_auto_pc_0} -quiet] -quiet

# XDC: c:/FPGA_project/AXI_UART_RX/AXI_UART_RX.gen/sources_1/bd/UART_RX_BD/UART_RX_BD_ooc.xdc
