# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AXI_UART_TX.xdc

# Block Designs: bd/AXI_UART_TX/AXI_UART_TX.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_TX || ORIG_REF_NAME==AXI_UART_TX} -quiet] -quiet

# IP: bd/AXI_UART_TX/ip/AXI_UART_TX_myip_slave_lite_v1_0_0_0/AXI_UART_TX_myip_slave_lite_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_TX_myip_slave_lite_v1_0_0_0 || ORIG_REF_NAME==AXI_UART_TX_myip_slave_lite_v1_0_0_0} -quiet] -quiet

# IP: bd/AXI_UART_TX/ip/AXI_UART_TX_processing_system7_0_0/AXI_UART_TX_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_TX_processing_system7_0_0 || ORIG_REF_NAME==AXI_UART_TX_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_UART_TX/ip/AXI_UART_TX_axi_interconnect_0_0/AXI_UART_TX_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_TX_axi_interconnect_0_0 || ORIG_REF_NAME==AXI_UART_TX_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/AXI_UART_TX/ip/AXI_UART_TX_rst_ps7_0_50M_0/AXI_UART_TX_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_TX_rst_ps7_0_50M_0 || ORIG_REF_NAME==AXI_UART_TX_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/AXI_UART_TX/ip/AXI_UART_TX_my_UART_tx_0_0/AXI_UART_TX_my_UART_tx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_TX_my_UART_tx_0_0 || ORIG_REF_NAME==AXI_UART_TX_my_UART_tx_0_0} -quiet] -quiet

# IP: bd/AXI_UART_TX/ip/AXI_UART_TX_auto_pc_0/AXI_UART_TX_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_UART_TX_auto_pc_0 || ORIG_REF_NAME==AXI_UART_TX_auto_pc_0} -quiet] -quiet

# XDC: c:/FPGA_project/AXI_UART/AXI_UART.gen/sources_1/bd/AXI_UART_TX/AXI_UART_TX_ooc.xdc
