# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zynq_axi_7seg.xdc

# Block Designs: bd/zynq_axi_7seg_bd/zynq_axi_7seg_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_7seg_bd || ORIG_REF_NAME==zynq_axi_7seg_bd} -quiet] -quiet

# IP: bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_processing_system7_0_0/zynq_axi_7seg_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_7seg_bd_processing_system7_0_0 || ORIG_REF_NAME==zynq_axi_7seg_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_my_tick_gen_0_0/zynq_axi_7seg_bd_my_tick_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_7seg_bd_my_tick_gen_0_0 || ORIG_REF_NAME==zynq_axi_7seg_bd_my_tick_gen_0_0} -quiet] -quiet

# IP: bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_rst_ps7_0_100M_0/zynq_axi_7seg_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_7seg_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_axi_7seg_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_ps7_0_axi_periph_0/zynq_axi_7seg_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_7seg_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_axi_7seg_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_my_display_0_1/zynq_axi_7seg_bd_my_display_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_7seg_bd_my_display_0_1 || ORIG_REF_NAME==zynq_axi_7seg_bd_my_display_0_1} -quiet] -quiet

# IP: bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_axi_slve_0_4/zynq_axi_7seg_bd_axi_slve_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_7seg_bd_axi_slve_0_4 || ORIG_REF_NAME==zynq_axi_7seg_bd_axi_slve_0_4} -quiet] -quiet

# IP: bd/zynq_axi_7seg_bd/ip/zynq_axi_7seg_bd_auto_pc_0/zynq_axi_7seg_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_7seg_bd_auto_pc_0 || ORIG_REF_NAME==zynq_axi_7seg_bd_auto_pc_0} -quiet] -quiet

# XDC: c:/FPGA_project/zynq_axi_7seg/zynq_axi_7seg.gen/sources_1/bd/zynq_axi_7seg_bd/zynq_axi_7seg_bd_ooc.xdc
