set_property IOSTANDARD LVCMOS33 [get_ports rst_0]
set_property PACKAGE_PIN D20 [get_ports rst_0]
set_property IOSTANDARD LVCMOS33 [get_ports parity_error_0]
set_property IOSTANDARD LVCMOS33 [get_ports RXD_0]
set_property PACKAGE_PIN L15 [get_ports parity_error_0]
set_property PACKAGE_PIN Y16 [get_ports RXD_0]


connect_debug_port dbg_hub/clk [get_nets clk]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list UART_RX_BD_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[0]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[1]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[2]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[3]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[4]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[5]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[6]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[7]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[8]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[9]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[10]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[11]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[12]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[13]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[14]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[15]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[16]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[17]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[18]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[19]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[20]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[21]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[22]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[23]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[24]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[25]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[26]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[27]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[28]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[29]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[30]} {UART_RX_BD_i/myip_slave_lite_v1_0_0/inst/slv_reg0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {UART_RX_BD_i/UART_RX_ctl_0/inst/data_out[0]} {UART_RX_BD_i/UART_RX_ctl_0/inst/data_out[1]} {UART_RX_BD_i/UART_RX_ctl_0/inst/data_out[2]} {UART_RX_BD_i/UART_RX_ctl_0/inst/data_out[3]} {UART_RX_BD_i/UART_RX_ctl_0/inst/data_out[4]} {UART_RX_BD_i/UART_RX_ctl_0/inst/data_out[5]} {UART_RX_BD_i/UART_RX_ctl_0/inst/data_out[6]} {UART_RX_BD_i/UART_RX_ctl_0/inst/data_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {UART_RX_BD_i/UART_RX_ctl_0/inst/reg_out[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {UART_RX_BD_i/UART_RX_ctl_0/inst/CNT_11[0]} {UART_RX_BD_i/UART_RX_ctl_0/inst/CNT_11[1]} {UART_RX_BD_i/UART_RX_ctl_0/inst/CNT_11[2]} {UART_RX_BD_i/UART_RX_ctl_0/inst/CNT_11[3]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
